# Generated by Django 4.2.7 on 2023-11-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(choices=[('Professor EBTT', 'Professor EBTT'), ('Técnico Administrativo', 'Técnico Administrativo'), ('Terceirizado', 'Terceirizado'), ('Aluno', 'Aluno'), ('Visitante', 'Visitante'), ('Outro', 'Outro')], max_length=22)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('biometria', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
