# Generated by Django 4.2.7 on 2023-12-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_servidor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Emprestada', 'Emprestada'), ('Livre', 'Livre')], max_length=22)),
                ('codbarra', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
