# Generated by Django 4.2.7 on 2023-12-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('id_chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chave')),
                ('id_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servidor')),
            ],
        ),
    ]
