# Generated by Django 4.2.7 on 2023-12-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_chave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='status',
            field=models.CharField(choices=[('Emprestada', 'Emprestada'), ('Livre', 'Livre')], max_length=22),
        ),
    ]
