# Generated by Django 4.2.7 on 2023-12-15 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_chave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(auto_now_add=True)),
                ('id_chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chave')),
            ],
        ),
    ]
